name: Review Assign

on:
  pull_request:
    types: [opened, ready_for_review]

env:
  REVIEWERS: 'morikann'

jobs:
  assign:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Assign Reviewer
        uses: hkusu/review-assign-action@v1
        with:
          assignees: ${{ github.actor }}
          reviewers: ${{ env.REVIEWERS }}
          ready-comment: 'Ready for review :rocket:'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}